### ISSUE TITLE
Problem processing additional mailboxes

### ISSUE THREAD

**Issue by alexaxb** [AdhocAdam/smletsExchangeConnector#212] opened 2020-10-13 14:20 UTC
**Describe the bug**
Processing two additional mailboxes fail with error: Cannot find an overload for "add" and the argument count: "2".

**Help us reproduce the bug**
Version of the connector you are using: 2.3
Features/variables you have enabled (i.e. $enableAzureCognitiveServicesForNewWI):

**Expected behavior**
Process the additional mailboxes

**Location and Environment**
Where are you running this from? Task Scheduler? SMA? Workflow server?: Task Scheduler
What SCSM version are you running? (i.e. 2012R2, 2016, 2016 UR3, 1801, etc.): 2019

**Additional context**
The code seems to fail on row 559:
```powershell
if ($UseMailboxRedirection -eq $true) {
    $Mailboxes.Add(@{$workflowEmailAddress = @{"DefaultWiType"=$defaultNewWorkItem;"IRTemplate"=$DefaultIRTemplateGuid;"SRTemplate"=$DefaultSRTemplateGuid;"PRTemplate"=$DefaultPRTemplateGuid;"CRTemplate"=$DefaultCRTemplateGuid};})
}
```
The solution seems to be that I need to declare the Mailbox array as an arraylist before filling it on row 246 like this:

```powershell
if ($smexcoSettingsMPMailboxes) {[System.Collections.ArrayList]$Mailboxes += $smexcoSettingsMPMailboxes | foreach-object {@{$_.MailboxAddress = @{"DefaultWiType"="$($_.MailboxTemplateWorkItemType)";"IRTemplate"="$($_.MailboxIRTemplateGUID)";"SRTemplate"="$($_.MailboxSRTemplateGUID)";"PRTemplate"="$($_.MailboxPRTemplateGUID)";"CRTemplate"="$($_.MailboxCRTemplateGUID)"};}}}
```

**Comment by AdhocAdam** [comment] 2020-10-17 20:06
Hey @alexaxb thanks for bringing this up!

I'm able to reproduce the issue your citing, but I can't reproduce with your suggested fix. Instead I've reworked the area in 559 you mention as follows. Can you let me know if the following works for you?

```powershell
    $Mailboxes.add(@{"$($workflowEmailAddress)" = @{"DefaultWiType"="$($defaultNewWorkItem)";"IRTemplate"="$($DefaultIRTemplateGuid)";"SRTemplate"="$($DefaultSRTemplateGuid)";"PRTemplate"="$($DefaultPRTemplateGuid)";"CRTemplate"="$($DefaultCRTemplateGuid)"};})
```

**Comment by AdhocAdam** [comment] 2020-11-06 18:39
Just following up on this @alexaxb

**Comment by alexaxb** [comment] 2020-11-10 09:00
Hey @AdhocAdam 
Have just tested it, but that does not work either.

**Comment by AdhocAdam** [comment] 2021-01-20 23:39
Reference to #259 by @Nathan-CPSD

**Comment by Nathan-CPSD** [comment] 2021-01-21 13:58
@AdhocAdam Taking a look at this reference now, to give you the info about our system
Connector Version. 3.1 (Current Release)
SCSM 1807
Workflow Implantation

I have restarted the server this morning as well will be looking at implementing the proposed fix on line 559 that you mention above and will report back. 

If there are any other details that you need to know please let me know.

**Comment by Nathan-CPSD** [comment] 2021-01-21 14:12
After system restart and code change (New Line in 3.1 is 716) the follow like, but slightly changed error:
A Windows Workflow Foundation workflow failed during execution.
 
Workflow Type: SMLets.Exchange.Connector.Resources.RunScript 

Workflow Identifier: 7bdb4c11-31b8-bf66-e2ef-54de5d109462 

Exception Type: System.Management.Automation.MethodInvocationException 

Exception Message: Exception calling "Add" with "1" argument(s): "Collection was of a fixed size." 

Exception Stack:    at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
   at CallSite.Target(Closure , CallSite , Object , Hashtable )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

**Comment by Nathan-CPSD** [comment] 2021-01-21 14:28
Update: Further testing: 
Edited the Workflow from trying to create SR to IR, no change > Reverted Back.
Disabled the multi-mailbox and the error changed to the following:

A Windows Workflow Foundation workflow failed during execution.
 
Workflow Type: SMLets.Exchange.Connector.Resources.RunScript 

Workflow Identifier: 7bdb4c11-31b8-bf66-e2ef-54de5d109462 

Exception Type: System.Management.Automation.ActionPreferenceStopException 

Exception Message: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: A discovery data item was rejected because the item is already bound to another Membership relationship. 

Exception Stack:    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input, Hashtable errorResults, Boolean enumerate)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)


A couple of notes: I still have the old Exchange Connector running on different mailboxes and using a different run as account, but there are currently 9 connectors are currently in place and working.   

My next step was to disable all of the connectors in order to attempt a clean test of the new connector. 

Also with the current error and the previous two, I have not had any updates to the logs stating that it was connecting to Exchange so it does not seem to progressing that far in the process, and is failing before hand.  I have yet to dig into the script to locate the break.

**Comment by AdhocAdam** [comment] 2021-01-21 18:05
That's interesting because it actually sounds like you've made it to Apply-SCSMTemplate with that error (line 3853).

https://github.com/AdhocAdam/smletsexchangeconnector/blob/0f3edf7aae77b9c7e29830d473123e5df39aefc6/smletsExchangeConnector.ps1#L3838-L3854

On the topic of logging, I assume logging level is set to 4, the type set to Workflow, and that in the SCSM Workflow server's Event Log you have the SMLets Exchange Connector log?

![loggging](https://user-images.githubusercontent.com/6636040/105392533-efdd6d00-5be0-11eb-8deb-c245eab50634.PNG)

**Comment by Nathan-CPSD** [comment] 2021-01-21 18:22
I do have logging enabled, set for level 4 and Logging type set for Workflow. 

I have been able to get the connector to successfully work, with one of my test account that I am using. 

I added it as the only account in the Multi-Mailbox.

The other change I made was moving away from using Exchange OWA to place the redirect rule in for the mailbox and moving as recommended in the Wiki (https://github.com/AdhocAdam/smletsexchangeconnector/wiki/Configuring-for-Multiple-Inboxes-(Email-Redirection,-not-Forwarding)).  This allowed the mail to be picked up properly from the redirected address.

Next I added the secondary test account to the list of multi-mailboxes and adjusted the targetAddress attribute in AD to match the collection account. 

Sent an email to both test account and watched them deliver to the collection email account specified. 

Allowed the collector to work and error reverted back to: 
A Windows Workflow Foundation workflow failed during execution.
 
Workflow Type: SMLets.Exchange.Connector.Resources.RunScript 

Workflow Identifier: 7bdb4c11-31b8-bf66-e2ef-54de5d109462 

Exception Type: System.Management.Automation.MethodException 

Exception Message: Cannot find an overload for "add" and the argument count: "2". 

Exception Stack:    at CallSite.Target(Closure , CallSite , Object , String , Hashtable )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at System.Management.Automation.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

As well event were not populating in the SMLets Exchange Connector Log. The Last events that I have are from the successful gather of the pervious single account in the multi-mailbox test. 

Currently 3 account are in place:
The collectionAccount used as the run-as account and mailbox that is setup in the Connector as the Workflow Email Address. 
TestAccount 1 -Specified in the Multi-Mailbox Section and currently has the Collection account set as Target Address. 
TestAccount 2 -Specified in the Multi-Mailbox Section and currently has the Collection account set as Target Address.

**Comment by AdhocAdam** [comment] 2021-01-21 18:28
Well the good news is now we're back to the error that _is_ this issue.

Exception Message: Cannot find an overload for "add" and the argument count: "2".

**Comment by AdhocAdam** [comment] 2021-01-22 18:06
Was looking at this more in depth last night and I believe I've found the middle ground between the two different proposed PowerShell line replacements above and the issue itself.

1. The idea for multi-mailbox is that first all the additional Mailboxes and their Templates are loaded into a variable called $Mailboxes. This is seen on line 383
2. Then the primary SCSM address is added to the $Mailboxes variable before the processing run. This is seen on line 716

I believe the nature of the problem here is that in step 1 above, it's creating an Object[] instead of hashtable. As a result, the subsequent addition of the primary inbox is hit and miss. The issue is then further compounded because PowerShell is then unable to perform hashtable based searches e.g. $hashtable["ValueIWant"] within Get-TemplatesByMailbox function.

All of this said, I believe the issue can be addressed by changing the initial declaration of the $Mailboxes variable. This slight reformatting ensures $Mailboxes is created as a hashtable datatype on Line 383 as follows:

```powershell
if ($smexcoSettingsMPMailboxes) {$smexcoSettingsMPMailboxes | foreach-object {$Mailboxes += @{$_.MailboxAddress = @{"DefaultWiType"="$($_.MailboxTemplateWorkItemType)";"IRTemplate"="$($_.MailboxIRTemplateGUID)";"SRTemplate"="$($_.MailboxSRTemplateGUID)";"PRTemplate"="$($_.MailboxPRTemplateGUID)";"CRTemplate"="$($_.MailboxCRTemplateGUID)"}}}}
```

This should result in a hashtable instead of an Object[] and a correct multi-mailbox run.

**Comment by Nathan-CPSD** [comment] 2021-01-25 13:49
Hope the weekend found you well, I implemented the new line 383 this morning, and results are positive.  

Line 716 has been reverted back to the previous version as the updated line from above cause the process not to run. 

With Line 383 in place the below are the results:
Example 1:
Account 1 Solo is picked up and created correctly and successfully, message is cleared from the inbox as expected. 
Example 2:
Account 2 solo is picked up created but not with a template and void of assigned and affected users and the email is not cleared out of the inbox or marked as read. 

The following error also is present in the Ops Mgr Log:
A Windows Workflow Foundation workflow failed during execution.
 
Workflow Type: SMLets.Exchange.Connector.Resources.RunScript 

Workflow Identifier: 7bdb4c11-31b8-bf66-e2ef-54de5d109462 

Exception Type: System.Management.Automation.ActionPreferenceStopException 

Exception Message: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: A discovery data item was rejected because the item is already bound to another Membership relationship. 

Exception Stack:    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input, Hashtable errorResults, Boolean enumerate)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

Looking at the SMLets Exchange Connector Log with the above error is received during the same run the process logs creation and picks up users names correctly, but final Processed x of x is not present, the log stops and then the above error is in the Ops Mgr log. 

When both Account 1 and 2 email at the same time then the both of the emails will results in the example 2.

**Comment by Nathan-CPSD** [comment] 2021-01-25 14:33
As a test to verify accounts, I did create a new account and new email, setting the TargetAddress as needed and used it as the Account 2 to make sure the second account did not have an issue I was not seeing.   All results were the same as above.

**Comment by AdhocAdam** [comment] 2021-01-25 15:25
Pretty decent weekend. But this was certainly in my head for all of it as I was anxiously awaiting your response 😄 

I've created a new branch _dev-3.x-MultiMailboxFix_ and opened a draft pull request to track changes as we work towards a resolution. I'll continue to look into this later today.

Thanks for your feedback so far!

**Comment by AdhocAdam** [comment] 2021-01-25 19:32
WIki article has been updated with a purely Exchange Configuration rather than PowerShell. It _should not_ make a difference but just a heads up.

**Comment by Nathan-CPSD** [comment] 2021-01-25 20:06
That was the initial way that I configured the redirect, as adding in TargetAddress does cause errors in EAC. I found that when a redirect is done via Exchange (Mailbox Rules) that it would not apply the template, assigned user or affected user when mail was picked up (Much like example 2 above).  I did not compare headers of the two messages but something is appended. 

When collection emails is set as the Target Address, the mail is delivered directly to the collection address, and with the  mailbox redirect, it is delivered to the redirected mailbox then redirected to the collection mailbox (The email will also be noted in Outlook as being auto-forwarded.   
 
 I will conduct a bit more testing but the above has been consistent thus far.

**Comment by Nathan-CPSD** [comment] 2021-01-25 20:18
Good update. No difference in results, but definitely recommended to use the Exchange Configuration rather then the TargetAddress Attribute which caused errors if you attempt to modify the account in EAC.

**Comment by AdhocAdam** [comment] 2021-01-25 20:18
If you start ISE/Code as the account that does the authentication to Exchange (e.g. the account configured on the General page), then run it manually, I'd be interested to know how Get-TemplatesByMailbox runs. From the sounds of it, it produces no matches, returns no templates and thus errors out as you described above on Line 3853.

I believe line 3051 declares it - **function Get-TemplatesByMailbox ($message)**. Then breakpoint the first line inside of it. You'll be able to inspect the message in question through $message and compare matching criteria.

**Comment by AdhocAdam** [comment] 2021-01-26 06:24
Just a heads up that I pushed another change to the branch which can be seen on #261 to introduce logging to the Get-TemplatesByMailbox function to help you/us further pinpoint this down.

**Comment by Nathan-CPSD** [comment] 2021-01-26 13:45
I updated the file version to match #261.  The Logging shows that the template identification is successful for both accounts and both process when looking at the logs.  The second account is missing two log entries that the first has which are the following:

The second New-WorkItem that gives final created information about the SR is not located in the logs for the second account.

As well the Final General Message that states Processed 1 of 2. 

The process in the logs stop after the Get-SCSMUserbyEmailAddress is logged, which is a success.  

 I have exported the event from this morning and have sent them to you via email.

**Comment by AdhocAdam** [comment] 2021-01-26 20:10
Just to make sure I have a similar setup here because I'm struggling to repro now after the line 383 change. I know your example has two messages...but is it for 1 primary + 2 additional inboxes? Or is it the primary + 1 additional inbox?

Second - the messages in question you are testing with have just a single To? or multiple To's?

Finally - are you using Templates that came stock SCSM? or did you create them?

**Comment by Nathan-CPSD** [comment] 2021-01-26 20:23
The setup that I am currently using is as follows.  
1 collection Email account (Workflow account/primary) No direct mail sent to this account, only redirects
2 secondary Email address/accounts that are being redirected to the Collection Inbox.  (With the hopes to add more once the issue is resolved)

Each message that I have sent has been a single To:

The template I am using are all created by myself, some copied from others. 

For another test I will go ahead and make new templates and try again to make sure that the template is not an issue in the equation.  Just to be strait forward about the plan, I will create new templates from scratch, and will not copy or duplicate any existing templates in hopes of getting clean results.

**Comment by Nathan-CPSD** [comment] 2021-01-26 20:58
Results:
New Templates were created for both of the test emails. 
The test from each of the test emails were successful. 

Double verified by adding in a third account and using one of the new templates, creation was successful. 

I am assuming that one of the templates that I used was duplicated from one of the Stock SCSM templates, and that was causing an issue with the template assignment.

**Comment by AdhocAdam** [comment] 2021-01-26 21:03
That is AWESOME to hear @Nathan-CPSD! A huge thanks for back n forth on this, it's absolutely appreciated.

I _may_ make some further logging adjustments to Get-TemplatesByMailbox (and of course open if you have any ideas either), but either way the fix will be wrapped into #257.

**Comment by Nathan-CPSD** [comment] 2021-01-26 21:11
@AdhocAdam More the happy to help, this is a great project you have, and much needed for the community. 

The additional logging that was added for this troubleshooting is a great addition, and am happy to hear that it will make it into the final code, If I think of anything that could further the process I will let you know.

Thanks again for all of your work!

**Comment by AdhocAdam** [comment] 2021-01-26 21:22
Many thanks. Always glad to know this project is helping folks.

[Wiki](https://github.com/AdhocAdam/smletsexchangeconnector/wiki/Configuration-Examples) has been updated to mention use of new/custom templates for primary _and_ secondary mailboxes per our discussion above.

**Comment by AdhocAdam** [comment] 2021-01-27 04:12
Pull Request has been completed into dev branch with changes originating from this thread. Will ship on next release via #257.

**Closed as completed by AdhocAdam** 2021-01-27 04:12 UTC
Labels: bug
